### ISSUE TITLE
Plain provisioner should pivot between bundles with overlapping CRDs

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#146]
The current CRD handling conflicts with the usage of the underlying helm library. Helm does not by default supporting updating CRDs, it ignores them. The goal is to be able to support updating bundles with CRDs in them, as a prerequisite to more complex CRD validation that is part of #93. This work may include removing the usage of Helm as an underlying library and moving to a more generic apply of resources. These resources should be ordered when applied in an intuitive way, and we may also want to support a rollback mechanism that helm supports. Helm also prevents rollout of bundles that have overlapping resources.

**Comment by joelanford** [comment]
Just to clarify, the current behavior _does_ support updating CRDs because the provisioner [puts all of the bundle objects into the dynamically created Helm chart's templates](https://github.com/operator-framework/rukpak/blob/60f8c3a55259635951581f0ce872ef927ca82435/provisioner/plain-v0/controllers/bundleinstance_controller.go#L145-L161), rather than segmenting the CRDs into the Helm chart using Helm's [CRD lookup logic](https://github.com/helm/helm/blob/e9abdc5efe11cdc23576c20c97011d452201cd92/pkg/chart/chart.go#L136-L151).

Helm upgrades all of the templates during a `helm upgrade`, so CRD changes are applied when CRDs are "templates" in the Chart.

However there _are_ two issues with the current behavior:
1. Helm doesn't do any CRD update checks to ensure a CRD upgrade is "safe" (e.g. won't result in data loss)
2. Helm can't handle an install/upgrade when a chart's templates contain both a CRD and an instance of the CRD.

We could solve (1) by using a validating client proxy or validating webhook. However, solving (2) likely requires special handling of the CRDs in the provisioner so that we can choreograph the process of applying the CRD updates, refreshing discovery so that the dynamic client knows the correct REST endpoints for the new CRD, then applying the object(s) that are of the CRD's GVK.

**Comment by exdx** [comment]
Thanks for that additional context @joelanford, I think there was some confusion around whether the current iteration supports pivoting between bundles with CRDs in them (the original thought was no) and therefore the thought was that removing Helm was a prereq to adding more CRD validation like you pointed out in [1]. 

Personally, if we can get CRD upgrades via the current process (with the two shortcomings that you pointed out) then we don't have to rip out the Helm stuff right away to make progress. This issue might be worth closing as a no-op in that case.

**Comment by exdx** [comment]
Closing this as the original scope of the ticket is no longer required. Removing the helm library is not a prerequisite to delivering more advanced functionality around CRD management in rukpak. The following two tickets are more valuable in the short-term and should be tackled instead:
- https://github.com/operator-framework/rukpak/issues/93
- https://github.com/operator-framework/rukpak/issues/131
