### ISSUE TITLE
Deploy an in-cluster image registry that stores e2e images

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/rukpak#280]
The e2e tests are using only images loaded in the kind currently.  It it is necessary to test with the real registries for https://github.com/operator-framework/rukpak/pull/279 changes

**Comment by exdx** [comment]
One option is to deploy a docker registry alongside the e2e tests and reference images directly from the internal registry. This is nice because there are no external dependencies on image registries, which can cause flakes and other issues. 

In operator-registry we bootstrap an image registry as part of the tests, see https://github.com/operator-framework/operator-registry/blob/master/scripts/start_registry.sh for the script that creates the registry

**Comment by akihikokuroda** [comment]
@timflannagan I would like to try this.  Is it OK?

**Comment by timflannagan** [comment]
Yeah that's fine with me. I'll mark you as the assignee, and we can attach this to a release milestone once we get a better idea when this kind of work would land.

**Comment by timflannagan** [comment]
/retitle Deploy in-cluster image registry that stores e2e images
