### ISSUE TITLE
Add support for opting out of specific CRD validation checks

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#289]
Goal: update the CRD validator component and enable users the ability to opt out of default behavior.

See https://github.com/operator-framework/rukpak/pull/268#discussion_r861943464 for more information.

**Comment by timflannagan** [comment]
Note: it's unclear whether this is behavior we should be supporting, but it felt worth tracking so we don't lose context in the short term. Throwing this in the backlog in the meantime.

**Comment by joelanford** [comment]
Just to elaborate a little on my [comment](https://github.com/operator-framework/rukpak/pull/268#discussion_r861943464), my thinking is that we should _replace_ the catch-all `core.rukpak.io/safe-upgrade-validation` with the more explicitly named annotations, so that we avoid leaving users with the impression that our webhook can effectively and fully prevent unsafe upgrades (which it can't).

**Comment by tylerslaton** [comment]
Closing this issue out in favor of talking about the general future of the CRD Validator component via a discussion thread.

https://github.com/operator-framework/rukpak/discussions/589
