### ISSUE TITLE
Support deploying rukpak to non-kind clusters

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#312]
Currently, the only way to deploy rukpak is through the `run` target, which assumes that the cluster being deployed to is a kind cluster (it attempts to `kind load` the provisioner image onto the cluster). Other targets to deploy rukpak were removed in #209 because they were potentially confusing to new users of the project. That said, Rukpak should provide a way to deploy itself to a non-CI cluster.

A/C:
- provide a makefile target that enables rukpak to be deployed to a live cluster (based on a real tag)
- update documentation to reflect the possibility of installing to a non-CI cluster

**Comment by exdx** [comment]
Going to put this in 0.5 to force us to triage this

**Comment by joelanford** [comment]
Devil's advocate: 
> provide a makefile target that enables rukpak to be deployed to a live cluster (based on a real tag)

That seems like it could be outside the scope of a Makefile target. Would it be required to specify a version? If not, what version would be make the default? If the version is specifiable, what do we do if we need to change the install method between versions? Would we have to include logic along the lines of `if [[ $version < "0.3.0" ]]; do $x; else do %y; fi`?

If we had a default, would that mean that we'd have to have a release commit prior to pushing a tag, such that the tagged commit's Makefile would refer to itself? I _really_ think we should avoid that because it makes release workflows much more difficult.

I'm all for having a way to deploy rukpak to non-kind clusters, but I feel like we already have that via the instructions on our release page. (e.g. "Installation" section here: https://github.com/operator-framework/rukpak/releases/tag/v0.3.0)

If that's insufficient, maybe we should think about a helm chart release? Or even more interesting -- a plain manifest bundle release that is somehow bootstrappable, such that rukpak upgrades after the initial installation would just be updates to the rukpak bundle instance to refer to the new rukpak version?

**Comment by timflannagan** [comment]
> I'm all for having a way to deploy rukpak to non-kind clusters, but I feel like we already have that via the instructions on our release page. (e.g. "Installation" section here: https://github.com/operator-framework/rukpak/releases/tag/v0.3.0)

I think this is where I largely land as well, and maybe this is just a documentation gap right now as I don't think we call this out anywhere in the root README which feels like it should have a dedicated header for installation instructions. Any quickstart or dev-based guide could then use the `run` Makefile target to quickly bootstrap the rukpak stack on kind clusters.

**Comment by exdx** [comment]
Ok, I agree with the points stated here about the complexity of integrating a makefile target for deploying tagged releases. I think there is then a documentation gap, where in the main README we could have a specific section dedicated to installing rukpak (via the official release we provide). That can be a follow-up to resolve this issue.

**Comment by exdx** [comment]
Re: helm chart release we have #274 which I think we should consider in an upcoming release.

Upgrading rukpak via rukpak sounds like a fun way to push updates. We do need to solve the problem in an ergonomic way, it's something OLM currently lacks (see https://github.com/operator-framework/operator-lifecycle-manager/issues/2695)
