### ISSUE TITLE
Run unit tests in a container locally

### ISSUE THREAD

**Issue by tylerslaton** [operator-framework/rukpak#398]
## Summary
In a [recent discovery](https://github.com/operator-framework/rukpak/pull/377#discussion_r881954669), it was found that a hashing implementation we were using had behavior that varied across operating systems locally. In other words, our unit tests were failing if they were ran on Linux but were passing on MacOS. We should come up with a way that we avoid environment skew and gain confidence in our changes prior to opening PR's.

## Proposed Solution
Update our local `make test-unit` target to run the unit test suite inside of a container and thus avoid environment skew. This will avoid issues where the tests pass locally but fail in CI.

**Comment by exdx** [comment]
This relates to #423 and was originally motivated by the non-determinism we saw in the hashing implementation. 

Due to the high startup costs to the unit tests, and maintaining this solution over time, it does not seem likely that we would like to implement this. The SDK team also fielded a similar issue and decided not to containerize their unit tests.
