### ISSUE TITLE
Follow-ups from introduction of registry+v1 provisioner

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#406]
AC:
- [x] #428
- [ ] #429
- [x] #430
- [ ] #431
- [ ] #442 - Incorporate changes from #396

**Comment by tylerslaton** [comment]
Working on updating the registry+v1 documentation now.

**Comment by tylerslaton** [comment]
Documentation updated with #424

**Comment by awgreene** [comment]
This issue was brought up in the OLM's Issue Triage Meeting due to [this comment](https://github.com/operator-framework/rukpak/issues/442#issuecomment-1191807607) by @exdx, which points out that this has been a long living issue pulled from milestone to milestone.

@timflannagan and @tylerslaton were both in favor of closing this tracking issue and tracking each of the individual issues.

There will be a followup to determine and document how sets of issues that implement a feature will be tracked, and the issues described in this ticket will be updated to conform to the new model.
