### ISSUE TITLE
 Incorporate changes from new Bundle APIs

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#442]
#396 refactored the underlying Bundle filesystem representation and added a new conversion method to transform registry+v1 bundles to plain+v0 bundles. These new APIs should be incorporated in the logic of the respective provisioners. 

Part of #406

**Comment by exdx** [comment]
So when I wrote this, I assumed #396 was merged to main, but turns out it was merged into another branch, so the functionality still isn't present in the main branch. This is what you mentioned. 

This issue probably needs to be groomed, for the sake of clarity, and should remain in the backlog for now. 

I think #406 can also be closed and tracked via separate issues instead of one overarching issue that gets carried release to release.

**Comment by awgreene** [comment]
@exdx this issue was discussed in the upstream issue triage meeting. We've updated #67 to:
- point out that #396 hasn't merged into master and has post-merge comments that need addressing
- marked #396 as a `good first issue`

This ticket can then be completed once #67 is closed.

I believe that is enough to remove the `needs-grooming` label from this issue, but if you disagree please reopen and call out what else you'd like us to do.
