### ISSUE TITLE
Add support for managing kustomize-based bundles

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#572]
# Overview

Add support for managing kustomize-based bundle content.

## Goal

Be able to consume kustomize packaged bundle content via a dedicated kustomize provisioner.

## Summary

There's currently no first-class way for rukpak to manage bundle contents that are packaged using kustomize. Available workarounds require first rendering those kustomize configurations into a static set of YAML manifests, and then either leveraging the `rukpak run bundle` local reconciler or packaging those static set of YAML manifests in the plain bundle format.

## Misc. Notes

#460 introduced a bundledeployment provisioner that's responsible for sourcing and managing bundle content that's packaged using helm charts. The helm chart provisioner utilizes the BundleDeployment's spec.config field for overriding contents at runtime, and that seems like a pattern that's worth extending here.

**Comment by exdx** [comment]
My opinion is that we could merge kustomize support from within the plain provisioner, and avoid having a separate provisioner. Having it separate creates a potentially confusing UX. Say I have a top-level manifests directory with kustomize manifests in them. Should I use the kustomize provisioner? Or render them and use the plain provisioner? Can the git source support kustomize? Etc.

My idea is that we can at runtime inspect a bundle filesystem for a kustomize file. If it exists, render the manifests before applying them. If not, apply them as expected. Since this is new, it's backwards compatible w.r.t. the plain bundle format -- it's possible to add support for kustomize without breaking existing users.

**Comment by timflannagan** [comment]
I've been flip flopping on this since we talked in discord, but I think we've been pretty hesitant towards doing any magic under-the-hood, and attempting to identify plain vs. kustomize bundle formats in our core provisioner implementations may fall in that domain.

In terms of a UX, maybe the compromise is that the local reconciler is able to detect a plain vs. kustomize bundle format and handle setting the requisite unique provisioner IDs. It's unclear to me whether we're establishing a bad pattern with this approach, and we need to hesitant around producing skew between the local reconciler and on-cluster agents.

**Comment by akihikokuroda** [comment]
I can rework this PR once #575 is merged.  It should simplify changes a lot.
