### ISSUE TITLE
Add support for embedding Bundles in the BundleInstance spec

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#73]
Implement support in the BundleInstance API and the plain manifest bundle provisioner for embedding a Bundle spec as outlined in the [e2e strawman](https://hackmd.io/hppR60SiRGKPcqKQuByvVg?view#Instance-API).

**Comment by joelanford** [comment]
This seems super useful, and I'm a +1. However, I think we have to think carefully about this.

Disregarding the on-cluster problems of actually installing the same bundle content twice, what happens if two bundle instances specify the same bundle spec? Do we create two copies of the bundle content with two different bundle names, or do we somehow allow shared ownership of a common underlying bundle? I assume it'll be the former option?

**Comment by joelanford** [comment]
We also need to keep in mind the implications on pivoting, especially as it relates to a failed pivot where the original bundle content should be preserved.

**Comment by timflannagan** [comment]
Moving this as 0.1 candidate.

**Comment by exdx** [comment]
This issue relates to the concept of JIT unpacking that was brought up during a rukpak demo. JIT unpacking is unpacking of Bundle resources only when the BundleInstance is created -- this issue tackles that since the Bundle is created only when the BundleInstance is created (since the Bundle is embedded in the BI). 

The other side of this JIT behavior is cascade deletion -- when the BI is removed, remove the relevant bundle as well, so bundle artifacts do not pollute the cluster. This might be something that is also related to this issue. There could be the case where, if the Bundle is embedded in the BI, the BI has an ownerref on the Bundle, and when the BI is removed the Bundle is also removed.

**Comment by timflannagan** [comment]
Punting this to the 0.3 milestone: it's unclear whether this is something we'll need to support in the short term while we iterate towards an MVP.

**Comment by akihikokuroda** [comment]
> JIT unpacking is unpacking of Bundle resources only when the BundleInstance is created
This doesn't support [this](https://github.com/operator-framework/rukpak/tree/main/provisioner/plain-v0#make-bundle-content-available-but-do-not-install-it) use case.  So JIT unpacking may be good only the embedded bundle.

**Comment by timflannagan** [comment]
IIRC @bparees had that comment - Ben, any idea what use case you had in mind where JIT unpacking is beneficial? The only thing I can think of right now is we're persisting unpacked Bundle contents that may not get applied, so we're potentially bloating cluster environments with a series of unused ConfigMaps?

**Comment by timflannagan** [comment]
> when i see a design that says "we're going to create a bunch of configmaps over time

I think the ConfigMaps are just an implementation detail, and we could move towards a storage model where we can configure a provisioner deployment to store Bundle contents in-memory (e.g. through an emptyDir, or a PVC if you require retention) as we already have the abstractions in place. You could then sit an HTTP API on top of that internal, in-memory store to serve Bundle contents (hopefully) agnostic to the provisioner if external clients/controllers/etc. require access.

**Comment by exdx** [comment]
Alternate approach: provide a new API that combines the two resources. 

The motivation for this approach is from the deployment/pod spec analogy: when defining a deployment, the pod spec is defined in-line -- similar to the embedded Bundle/BI feature. The application is a single atomic operation.

**Comment by timflannagan** [comment]
Link to the proposed design hackmd: <https://hackmd.io/HNWfNUbqTUGAW5VRMcc40w?both>

**Comment by timflannagan** [comment]
Update: it sounds like we landed on a design and I moved that hackmd to the shared rukpak folder.
