### ISSUE TITLE
Support private bundle

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#81]
Currently there is no first-class way of supporting bundle images which are private, or underlying operator/operand images which are private as well. The initial prototype did include a `spec.Secrets` field which referenced secrets by name and copied them to the relevant namespace, but this was removed due to security concerns. 

Users of the system may store their bundle or underlying operator images in private registries. There should be an intuitive, documented way to use rukpak and the set of provisioners on-cluster with a Bundle image that is private, or if the underlying related images for a given BundleInstance are also private (for example, if the Deployment spec references a private image).

**Comment by joelanford** [comment]
For sourcing bundle images, it seems like we could:
- add a `spec.source.image.imagePullSecretName` field to the Bundle API and document that the secret must be present in the namespace that the provisioner is deployed to. That way we don't have to copy secrets anywhere.

For sourcing operator images, things are more difficult because we would need some way to:
- know what secrets to use and where to inject them
- actually inject the secret into the pod spec(s) that need them as the BI is being installed. (this sounds a lot like what the cert-manager injection annotations do)

Perhaps we should separate these problems into separate issues?

**Comment by exdx** [comment]
0.3 candidate

**Comment by exdx** [comment]
Potentially moving to 0.4

**Comment by nsapse** [comment]
Question - while this is a work in progress would it make sense from a UX perspective to have an error letting users know the reason their deployment is failing is the private source?

**Comment by timflannagan** [comment]
I'm going to move this out of the 0.4 milestone, as that milestone already has a good chunk of tickets already assigned. This seems like a solid 0.5 milestone candidate.

**Comment by akihikokuroda** [comment]
> Perhaps we should separate these problems into separate issues?

I agree.  The first issue is just for the image bundle and the second one applies for both github and image bundles.  I'll create a separate issue for the second one.
